version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: personal-finance-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-finance-api
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: